name: CV-BUILDER

on: [push]

jobs:
  build-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olivierodo/awesome-cv-action@0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'john-doe.tex'
